### ISSUE TITLE
ssm parameter env: do not wrap quotes when value contains spaces

### ISSUE THREAD

**Issue by kangaechu** [minamijoyo/myaws#58]
Hi!

Values in the AWS system parameter store can contain blanks. However, `myaws ssm parameter env` does not seem to care about including spaces in the value.

```shell
$ myaws ssm parameter put test.foo "a b c d"
$ myaws ssm parameter put test.bar "barbarbar"
```

## Expected behavior

Each value is wrapped by single quote, and retrieve environment variable correctly.

```shell
$ myaws ssm parameter env test
BAR='barbarbar' FOO='a b c d'

$ export $(myaws ssm parameter env test)
$ echo $FOO
a b c d
```

## Actual behavior

Each value is not wrapped, so It returns values I don't expect.

```shell
$ myaws ssm parameter env test
BAR=barbarbar FOO=a b c d

$ export $(myaws ssm parameter env test)
$ echo $FOO
a
```

**Comment by minamijoyo** [comment]
Fixed in v0.4.3 🚀
